version: '3.8'

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: products
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8001:8001"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 8001
    depends_on:
      - db
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    image: app:django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  postgres_data:
